name: Makefile CI python application with GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with pylint
        run: |
          pylint --disable=R,C hello.py

      - name: Test with pytest
        run: |
          pytest --verbose test_hello.py

      - name: Format Code
        run: |
          black *.py
